# Generated by Django 3.1.1 on 2020-09-24 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='age',
            field=models.CharField(default='', max_length=3),
        ),
    ]
