# Generated by Django 3.1.1 on 2020-09-24 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_auto_20200924_1106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='usn',
            new_name='fname',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='country',
            new_name='lname',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='age',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='state',
        ),
    ]
